services:
  postgres_dev:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_USER: ${POSTGRES_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_prod:
    image: postgres:15
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_PROD_DB}
      POSTGRES_USER: ${POSTGRES_PROD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD}
    ports:
      - "${POSTGRES_PROD_PORT}:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres_dev
      - postgres_prod
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_dev_data:
  postgres_prod_data:
  pgadmin_data:
